import { GraduationCap, Stethoscope, Cpu, Activity, Scale } from "lucide-react";

export type Course = {
  name: string;
  full: string;
  duration: string;
  eligibility: string;
  fee: string;
  careerScope: string;
  mode: string;
  bscc: boolean;
  hindiDesc: string;
  salary: string;
  entranceExam: string;
  govtJobs: string;
  topColleges: string[];
  highlights: string[];
};

export const teachingCourses: Course[] = [
  {
    name: "B.Ed",
    full: "Bachelor of Education",
    duration: "2 Years",
    eligibility: "Graduation with minimum 50% marks in any stream from a recognized university",
    fee: "₹50,000/yr",
    careerScope: "Government School Teacher (TET/CTET qualified), Private School Teacher, Education Officer, School Principal, Content Developer for EdTech companies. Bihar STET qualified B.Ed graduates get direct government job opportunities in middle & high schools.",
    mode: "Regular & Distance options available from NCTE-approved recognized Indian universities. Siksha Wallah guides students for both modes based on eligibility and career goals.",
    bscc: true,
    hindiDesc: "B.Ed Bihar का सबसे popular teaching course है। Graduation के बाद 2 साल का यह course करके आप government या private school में teacher बन सकते हैं। Bihar STET pass करने के बाद सरकारी नौकरी मिलती है। BSCC loan से fees का बोझ नहीं पड़ता।",
    salary: "₹25,000–₹55,000/month (Govt Teacher after STET)",
    entranceExam: "No entrance exam. Direct admission based on graduation marks. CTET/BTET required for govt job after course.",
    govtJobs: "Bihar STET (Secondary Teacher), CTET qualified Middle/High School Teacher, Education Officer, SCERT Trainer",
    topColleges: ["Patna University (Patna)", "BRA Bihar University (Muzaffarpur)", "VKS University (Ara)", "LNMU (Darbhanga)", "Magadh University (Bodh Gaya)"],
    highlights: ["Most popular course in Bihar for govt jobs", "BSCC loan up to ₹4 Lakh available", "Both Regular & Distance mode", "Bihar STET opens ₹40,000+/month govt teacher post"],
  },
  {
    name: "D.El.Ed",
    full: "Diploma in Elementary Education",
    duration: "2 Years",
    eligibility: "12th Pass (any stream) with minimum 50% marks. Age limit: 18–35 years",
    fee: "₹25,000/yr",
    careerScope: "Primary School Teacher (Class 1–8) in government and private schools, Anganwadi Supervisor, NGO Education Worker. BTET/CTET qualification opens government Primary Teacher posts across Bihar with excellent salary packages.",
    mode: "Regular mode from SCERT/state-approved institutions. Distance mode available from select NCTE-recognized universities. We assist with both options.",
    bscc: true,
    hindiDesc: "D.El.Ed (पहले BTC) 10th और 12th pass students के लिए primary school teacher बनने का सबसे सीधा रास्ता है। 2 साल के इस diploma के बाद Class 1–8 में teaching कर सकते हैं। Bihar में BTET पास करने पर सरकारी Primary Teacher की नौकरी मिलती है।",
    salary: "₹20,000–₹45,000/month (Govt Primary Teacher after BTET)",
    entranceExam: "No entrance exam. Admission based on 12th marks. BTET/CTET exam required for govt job after course.",
    govtJobs: "Bihar Primary Teacher (Class 1–5), Upper Primary Teacher (Class 6–8), Anganwadi Supervisor, SCERT Resource Person",
    topColleges: ["DIET Colleges (District level, Bihar)", "SCERT-affiliated institutions", "Patliputra University (Patna)", "BNMU (Madhepura)", "Munger University"],
    highlights: ["Only 12th pass required", "Lowest cost teaching course", "Govt Primary Teacher vacancy every year in Bihar", "BSCC loan available"],
  },
  {
    name: "B.P.Ed",
    full: "Bachelor of Physical Education",
    duration: "2 Years",
    eligibility: "Graduation (any stream) with minimum 50% marks. Physical fitness test required at most colleges. Age: 19–25 years",
    fee: "₹40,000/yr",
    careerScope: "Physical Education Teacher in Govt/Private Schools, Sports Coach, NCC Officer (civilian), Fitness Trainer, Sports Authority of India (SAI) Coach, Olympic/national-level sports trainer.",
    mode: "Regular mode from NCTE-approved colleges. Admission via state counselling or direct at private colleges. We guide for both.",
    bscc: true,
    hindiDesc: "B.P.Ed उन students के लिए है जो sports और physical education में career बनाना चाहते हैं। Graduation के बाद 2 साल का यह course करके Government School में Physical Education Teacher बन सकते हैं। BPSC/State PSC से PE teacher की permanent govt job मिलती है। SAI coaching centers में भी अच्छी opportunities हैं।",
    salary: "₹25,000–₹50,000/month (Govt PE Teacher / Sports Coach)",
    entranceExam: "Physical fitness test at most colleges. No written entrance in many states. State-level counselling for govt colleges.",
    govtJobs: "Govt PE Teacher (BPSC/State PSC), SAI Coach, NCC Officer (civilian), SSB Sports Quota, Defence Sports Wing",
    topColleges: ["Patna University (Patna)", "BRA Bihar University (Muzaffarpur)", "LNMU Darbhanga", "Magadh University", "HNBGU Srinagar (Uttarakhand)"],
    highlights: ["Govt PE teacher via BPSC — permanent job", "SAI coaching center opportunities", "Sports quota jobs in Govt/Railway/Bank", "BSCC loan available"],
  },
  {
    name: "M.Ed",
    full: "Master of Education",
    duration: "2 Years",
    eligibility: "B.Ed with minimum 55% marks from a UGC-recognized university",
    fee: "₹60,000/yr",
    careerScope: "College Lecturer (NET/SET qualified), School Principal, Curriculum Developer, Educational Researcher, Teacher Trainer, Academic Coordinator at SCERT/NCERT. M.Ed opens doors to PhD in Education and academic careers.",
    mode: "Regular mode from NAAC-accredited universities. Distance mode available from select institutions recognized by DEB (Distance Education Bureau). We guide based on your preference.",
    bscc: false,
    hindiDesc: "M.Ed teaching field की master degree है। B.Ed के बाद यह course करके आप college lecturer, school principal, या education researcher बन सकते हैं। NET/SET qualify करने पर university में professor की नौकरी मिलती है। Education में PhD का रास्ता भी M.Ed से खुलता है।",
    salary: "₹35,000–₹80,000/month (College Lecturer / NET qualified)",
    entranceExam: "Entrance test at most universities. UGC-NET/SET required for college lecturer post after M.Ed.",
    govtJobs: "College Lecturer (UGC-NET), SCERT Academic Staff, NCERT Researcher, Education Officer (State PSC), School Principal",
    topColleges: ["Patna University", "BRA Bihar University (Muzaffarpur)", "Magadh University", "LNMU Darbhanga", "Nalanda Open University"],
    highlights: ["Highest qualification in education field", "UGC-NET opens college professor career", "PhD in Education possible after M.Ed", "Principal & Academic leadership roles"],
  },
];

export const medicalCourses: Course[] = [
  {
    name: "MBBS",
    full: "Bachelor of Medicine & Bachelor of Surgery",
    duration: "5.5 Years (inc. 1-yr internship)",
    eligibility: "12th Science (PCB) with minimum 50% marks + NEET UG qualification. Age: 17+ years",
    fee: "₹8–25 Lakh/yr (varies by college)",
    careerScope: "Government Doctor (BPSC Civil Services), Private Hospital Specialist, Surgeon, Researcher, Medical Officer. MBBS graduates from recognized colleges are eligible for PG (MD/MS) entrance. Extremely high demand in Bihar's rural health sector.",
    mode: "Regular mode only from MCI/NMC-approved medical colleges. We guide for both government and private college admissions through NEET counselling.",
    bscc: false,
    hindiDesc: "MBBS भारत का सबसे prestigious medical course है। NEET पास करके government या private medical college में admission लें। 5.5 साल (internship सहित) के बाद आप डॉक्टर बनते हैं। Bihar के rural areas में government doctor की बहुत demand है। BPSC civil services से सरकारी नौकरी भी मिलती है।",
    salary: "₹70,000–₹1,50,000/month (Govt Doctor / BPSC Medical Officer)",
    entranceExam: "NEET UG (mandatory). Score 450+ for govt college. State quota & all-India quota counselling.",
    govtJobs: "BPSC Medical Officer, Railway Doctor, ESIC Medical Officer, Armed Forces Doctor (AFMC), NHM Medical Officer",
    topColleges: ["PMCH Patna (Govt)", "NMCH Patna (Govt)", "AIIMS Patna", "IGIMS Patna", "Darbhanga Medical College"],
    highlights: ["Highest paying medical degree", "NEET mandatory — start preparation early", "BPSC Medical Officer salary ₹1L+/month", "MD/MS specialization possible after MBBS"],
  },
  {
    name: "BAMS",
    full: "Bachelor of Ayurvedic Medicine & Surgery",
    duration: "5.5 Years (inc. 1-yr internship)",
    eligibility: "12th Science (PCB) minimum 50% marks + NEET UG qualification. Age: 17+ years",
    fee: "₹3,50,000/yr (Total ~₹15,75,000)",
    careerScope: "Ayurvedic Doctor, Panchakarma Specialist, Government AYUSH Medical Officer, Private Clinic Owner, Research in Ayurveda. Bihar and central government both recruit BAMS graduates as AYUSH Medical Officers. Growing demand with Ayurveda's rise in wellness sector.",
    mode: "Regular mode from CCIM-approved Ayurvedic colleges. NEET score required. We guide for state quota and management quota admissions across India.",
    bscc: false,
    hindiDesc: "BAMS Ayurvedic Medicine और Surgery का 5.5 साल का degree course है। NEET pass करके government या private Ayurvedic college में admission लें। AYUSH Medical Officer बनें, खुद का clinic खोलें, या research करें। MBBS से कम NEET score में doctor बनने का बेहतरीन रास्ता। Bihar में AYUSH dept में regular govt recruitment होती है।",
    salary: "₹40,000–₹1,20,000/month (AYUSH Medical Officer / Private Practice)",
    entranceExam: "NEET UG (mandatory). Less competition than MBBS. State AYUSH counselling for govt college seats.",
    govtJobs: "State AYUSH Medical Officer, NHM AYUSH Doctor, Railway AYUSH, ESIC AYUSH, Defence AYUSH Officer, CGHS",
    topColleges: ["Govt Ayurvedic College Patna", "Rajiv Gandhi Ayurved College Bhopal", "DY Patil Ayurvedic College", "SDM Ayurvedic College Karnataka", "BHU Faculty of Ayurveda Varanasi"],
    highlights: ["Less NEET competition than MBBS", "AYUSH Medical Officer ₹50,000+/month govt salary", "Own Ayurvedic clinic possible", "Rising demand in wellness & preventive healthcare"],
  },
  {
    name: "BDS",
    full: "Bachelor of Dental Surgery",
    duration: "5 Years (inc. 1-yr internship)",
    eligibility: "12th Science (PCB) with minimum 50% marks + NEET UG qualification",
    fee: "₹5–15 Lakh/yr",
    careerScope: "Private Dental Clinic Owner, Hospital Dental Surgeon, Government Dental Officer, MDS Specialist (Orthodontist, Endodontist). BDS graduates can also join dental product companies and public health programs.",
    mode: "Regular mode only from DCI-approved dental colleges. We provide complete NEET counselling guidance for state and all-India quota seats.",
    bscc: false,
    hindiDesc: "BDS dental surgeon बनने का course है। NEET qualify करके 5 साल में Dental Surgeon बनें। अपना private clinic खोलें या government hospital में काम करें। MDS (specialization) करने पर Orthodontist, Endodontist जैसे specialist बन सकते हैं।",
    salary: "₹40,000–₹1,00,000/month (Govt Dental Officer / Private Practice)",
    entranceExam: "NEET UG (mandatory). DCI-approved college through state/all-India quota counselling.",
    govtJobs: "Government Dental Officer (State PSC), ESIC Dental Surgeon, Railway Dental Officer, Armed Forces Dentist",
    topColleges: ["Patna Dental College (Govt)", "PMCH Dental Dept", "Buddha Institute of Dental Sciences (Patna)", "Awadh Dental College (Jharkhand)"],
    highlights: ["5-year course with 1-yr internship", "Own clinic possible after BDS", "MDS specialization for higher income", "NEET score 400+ needed for good college"],
  },
  {
    name: "B.Sc Nursing",
    full: "Bachelor of Science in Nursing",
    duration: "4 Years",
    eligibility: "12th Science (PCB or PCM+Biology) with minimum 45% marks (40% for SC/ST). Age: 17–35 years",
    fee: "₹60,000/yr",
    careerScope: "Staff Nurse in Government Hospitals (AIIMS, ESIC, Railway, Armed Forces), Private Hospitals, Nursing Tutor, Community Health Nurse. B.Sc Nursing is the most in-demand healthcare course with jobs across India and abroad (UK, Canada, Gulf countries).",
    mode: "Regular mode from INC (Indian Nursing Council) approved colleges. We help with both Bihar state quota and all-India private college admissions.",
    bscc: true,
    hindiDesc: "B.Sc Nursing healthcare sector का सबसे in-demand course है। 4 साल का यह degree course AIIMS, Railway, ESIC जैसे top government hospitals में Staff Nurse की नौकरी दिलाता है। विदेश (UK, Canada, Gulf) में भी भारतीय nurses की बहुत demand है। BSCC loan से fees cover होती है।",
    salary: "₹25,000–₹60,000/month (Govt Staff Nurse) | Higher abroad (UK/Canada)",
    entranceExam: "No NEET required. State-level nursing entrance or direct admission based on PCB marks.",
    govtJobs: "AIIMS Staff Nurse, ESIC Nurse, Railway Nurse, Armed Forces Nursing Officer (MNS), NHM Nurse, State Health Dept Nurse",
    topColleges: ["PMCH College of Nursing (Patna)", "IGIMS Nursing College (Patna)", "AIIMS Patna", "Shri Krishna Medical College Muzaffarpur", "Nalanda Medical College"],
    highlights: ["No NEET required — PCB 12th enough", "Jobs in AIIMS, Railway, ESIC, Army", "Foreign jobs (UK, Canada, Gulf) possible", "BSCC loan up to ₹4 Lakh available"],
  },
  {
    name: "GNM",
    full: "General Nursing & Midwifery",
    duration: "3 Years + 6-month internship",
    eligibility: "12th Pass (Science preferred, PCB). Minimum 40% marks. Age: 17–35 years",
    fee: "₹40,000/yr",
    careerScope: "Staff Nurse in Government & Private Hospitals, Community Health Worker, Midwife, Home Care Nurse. GNM nurses are eligible for government nursing recruitment exams (NHM, ESIC, Railway). High demand in Bihar's Primary Health Centers.",
    mode: "Regular mode from INC-approved nursing schools and colleges. Both government and private institutions available. BSCC loan assistance available for eligible students.",
    bscc: true,
    hindiDesc: "GNM 3 साल का nursing diploma है जो government और private hospitals में Staff Nurse की नौकरी दिलाता है। NHM, ESIC, और Railway में GNM nurses की regular भर्ती होती है। Bihar के Primary Health Centers में भी बहुत scope है। BSCC loan available है।",
    salary: "₹18,000–₹45,000/month (Staff Nurse in Govt/Private Hospital)",
    entranceExam: "State nursing entrance exam or direct admission. No NEET required.",
    govtJobs: "NHM Staff Nurse, ESIC Nurse, Railway Nurse, State Hospital Nurse, Community Health Nurse (PHC/CHC)",
    topColleges: ["GNM School PMCH Patna", "Muzaffarpur Nursing School", "Darbhanga Medical College", "SKMCH Muzaffarpur", "Various Private INC-approved colleges across Bihar"],
    highlights: ["3 years diploma — faster career start", "Regular govt recruitment under NHM Bihar", "PHC & CHC across Bihar hire GNM nurses", "BSCC loan available"],
  },
  {
    name: "ANM",
    full: "Auxiliary Nursing & Midwifery",
    duration: "2 Years",
    eligibility: "10th Pass (for girls only) from a recognized board. Age: 17–35 years",
    fee: "₹25,000/yr",
    careerScope: "ANM/ASHA Worker in Government Health Programs, Community Health Center Nurse, Health Education Worker, Sub-Center Nurse. Bihar government regularly recruits ANM graduates under NHM with good salary and job security.",
    mode: "Regular mode from INC-approved schools. Short duration and low-cost course — ideal for girls from rural areas seeking stable government healthcare jobs.",
    bscc: true,
    hindiDesc: "ANM सिर्फ लड़कियों के लिए 2 साल का nursing course है — केवल 10th pass होना जरूरी है। Bihar government NHM के तहत ANM की regular भर्ती करती है। गाँव के Primary Health Center और Sub-Center में stable government नौकरी मिलती है। कम fees, BSCC loan भी मिलता है।",
    salary: "₹12,000–₹30,000/month (ANM in Govt Health Programs)",
    entranceExam: "No entrance exam. Direct admission based on 10th marks. Only for female candidates.",
    govtJobs: "ANM under NHM Bihar, ASHA Supervisor, Sub-Center Nurse, PHC Health Worker, Govt Maternity Center Staff",
    topColleges: ["ANM Training Centers (District Hospitals)", "PMCH ANM School Patna", "Various District ANM schools across Bihar", "INC-approved private ANM schools"],
    highlights: ["Only 10th pass required", "For girls only — safe & secure career", "NHM Bihar recruits ANM regularly", "Lowest fees — BSCC loan available"],
  },
  {
    name: "D.Pharma",
    full: "Diploma in Pharmacy",
    duration: "2 Years",
    eligibility: "12th Science (PCB or PCM) with minimum 45% marks from recognized board",
    fee: "₹35,000/yr",
    careerScope: "Pharmacist in Government & Private Hospitals, Medical Stores, Drug Inspector (after experience), Medical Representative. D.Pharma is the fastest route to become a registered pharmacist — 2 years only. BSCC loan available.",
    mode: "Regular mode from PCI-approved pharmacy schools. Shorter and more affordable than B.Pharma. We guide for admissions across Bihar and nearby states.",
    bscc: true,
    hindiDesc: "D.Pharma 2 साल का pharmacy diploma है। 12th PCB/PCM के बाद सीधे Pharmacist बन सकते हैं। Hospital pharmacy, medical store, या medical representative — कई रास्ते हैं। B.Pharma से कम fees और कम time में registered pharmacist बनें। BSCC loan से fees cover होती है।",
    salary: "₹15,000–₹35,000/month (Hospital Pharmacist / Medical Store)",
    entranceExam: "State pharmacy entrance or direct admission. No NEET required. Bihar DCECE (pharmacy) for some govt colleges.",
    govtJobs: "Government Hospital Pharmacist (State PSC), ESIC Pharmacist, Railway Pharmacist, Army Pharmacist (through defence recruitment)",
    topColleges: ["Patna Sahib Pharmacy School", "Various PCI-approved private schools in Bihar", "RKDF Institute (Bhopal)", "Delhi Pharmaceutical Sciences & Research", "Galgotias School of Pharmacy (UP)"],
    highlights: ["Only 2 years — quickest pharmacy career", "Registered Pharmacist after D.Pharma", "Medical store / own pharmacy possible", "BSCC loan up to ₹4 Lakh available"],
  },
  {
    name: "BMLT",
    full: "Bachelor of Medical Lab Technology",
    duration: "3 Years + 6-month internship",
    eligibility: "12th Science (PCB or PCM+Biology) with minimum 45% marks. Age: 17–30 years",
    fee: "₹50,000/yr",
    careerScope: "Medical Lab Technician in Govt/Private Hospitals, Diagnostic Centers, Blood Banks, Pathology Labs. BMLT graduates work in AIIMS, ESIC, Railway hospitals. High demand across Bihar's growing diagnostic sector. Abroad opportunities in Gulf and UK.",
    mode: "Regular mode from AICTE/university-approved colleges. We assist with both Bihar state-level and private college admissions.",
    bscc: true,
    hindiDesc: "BMLT medical lab technology का 3 साल का bachelor course है। Blood tests, X-ray, pathology — इन सब में expert बनें। AIIMS, ESIC, Railway जैसे government hospitals में Lab Technician की नौकरी मिलती है। Private diagnostic centers में भी बहुत scope है। Gulf और UK में भी Indian BMLT graduates की demand है।",
    salary: "₹18,000–₹45,000/month (Govt Lab Technician / Private Diagnostic)",
    entranceExam: "No NEET required. State-level entrance or direct admission. PCB 12th required.",
    govtJobs: "AIIMS Lab Technician, ESIC Medical Lab Tech, Railway Lab Tech, NHM Lab Technician, State Hospital Lab Staff",
    topColleges: ["PMCH Patna (Govt)", "IGIMS Patna", "AIIMS Patna", "Shri Krishna Medical College Muzaffarpur", "Various private colleges in Bihar & Jharkhand"],
    highlights: ["Growing demand in diagnostic sector", "Govt jobs in AIIMS, Railway, ESIC", "Gulf/UK job opportunities", "BSCC loan available"],
  },
  {
    name: "B.Pharma",
    full: "Bachelor of Pharmacy",
    duration: "4 Years",
    eligibility: "12th Science (PCB or PCM) with minimum 45% marks from recognized board",
    fee: "₹55,000/yr",
    careerScope: "Pharmacist in Government Hospitals & Dispensaries, Drug Inspector, Quality Control Officer in Pharma Companies, Medical Representative, Clinical Research Associate, Retail Pharmacy Owner. B.Pharma graduates are eligible for government pharmacy exams.",
    mode: "Regular & Distance modes available from PCI (Pharmacy Council of India) and AICTE-approved institutions. We guide for both Bihar and out-of-state admissions.",
    bscc: true,
    hindiDesc: "B.Pharma 4 साल का pharmacy degree course है। Pharmacist, Drug Inspector, Medical Representative, या खुद की pharmacy shop — कई रास्ते हैं। Government hospital में pharmacist बनने का सपना B.Pharma से पूरा होता है। Pharma companies में भी अच्छी salary मिलती है। BSCC loan eligible है।",
    salary: "₹20,000–₹55,000/month (Govt Pharmacist / Pharma Company)",
    entranceExam: "State Pharmacy entrance or direct admission based on 12th PCB/PCM marks. No NEET required.",
    govtJobs: "Government Pharmacist (BPSC/State PSC), Drug Inspector, Hospital Pharmacy Manager, ESIC Pharmacist, Railway Pharmacist",
    topColleges: ["Patna Sahib Pharmacy College", "Galgotias College (UP)", "Bengal School of Technology", "RKDF University (Bhopal)", "Various PCI-approved colleges near Bihar"],
    highlights: ["Own medical store / pharmacy possible", "Drug Inspector via State PSC", "Pharma companies hire B.Pharma freshers", "BSCC loan up to ₹4 Lakh available"],
  },
];

export const technicalCourses: Course[] = [
  {
    name: "B.Tech",
    full: "Bachelor of Technology",
    duration: "4 Years",
    eligibility: "12th Science (PCM) with minimum 45% marks. JEE Main/State CET scores preferred",
    fee: "₹80,000/yr (varies by branch & college)",
    careerScope: "Software Engineer, Civil/Mechanical/Electrical Engineer, Government Engineer (BPSC/SSC JE), IT Company Employee, Startup Founder. B.Tech from AICTE-approved colleges is recognized for both private sector and government recruitment.",
    mode: "Regular mode from AICTE-approved colleges. We guide for JEE counselling, Bihar DCECE, and private B.Tech admissions with lateral entry options.",
    bscc: true,
    hindiDesc: "B.Tech engineering का 4 साल का degree course है। Computer Science, Civil, Mechanical, Electrical — अपना branch चुनें। JEE Main या Bihar DCECE से government college में admission पाएं। TCS, Infosys जैसी IT companies और BPSC/SSC JE से government engineer — दोनों रास्ते खुले हैं। BSCC loan available।",
    salary: "₹30,000–₹1,20,000/month (IT Companies / Govt Engineer)",
    entranceExam: "JEE Main (for NIT/central colleges). Bihar DCECE (for state govt colleges). Direct admission available at private colleges.",
    govtJobs: "BPSC Junior Engineer, SSC JE, BSPHCL Engineer, PWD Engineer, BRO (Border Roads), Defence Technical Officer",
    topColleges: ["NIT Patna", "BIT Mesra (Ranchi)", "GIET Gunupur", "Chandragupt Institute (Patna)", "LNCT (Bhopal)", "Galgotias University (UP)"],
    highlights: ["Highest salary potential among all courses", "IT companies: TCS, Infosys, Wipro campus recruitment", "Govt Engineer via SSC JE / BPSC JE", "BSCC loan up to ₹4 Lakh"],
  },
  {
    name: "Polytechnic",
    full: "Diploma in Engineering",
    duration: "3 Years",
    eligibility: "10th Pass with minimum 35% marks in any recognized board",
    fee: "₹30,000/yr",
    careerScope: "Junior Engineer in PWD/BSEB/NHAI, Factory Supervisor, Technical Assistant, ITI Instructor. Diploma holders can directly enter 2nd year B.Tech (Lateral Entry). Government jobs via BSSC and SSC JE after diploma.",
    mode: "Regular mode from AICTE-approved polytechnic colleges in Bihar and other states. Government polytechnic seats available at very low fees through DCECE counselling.",
    bscc: true,
    hindiDesc: "Polytechnic (Diploma in Engineering) 3 साल का course है जो 10th pass के बाद किया जा सकता है। इसके बाद B.Tech 2nd year में lateral entry मिलती है। PWD, BSEB, NHAI में Junior Engineer की नौकरी मिलती है। Government polytechnic में fees बहुत कम है — Bihar DCECE से सस्ती सीट पाएं।",
    salary: "₹18,000–₹45,000/month (Junior Engineer / Supervisor)",
    entranceExam: "Bihar DCECE (Diploma) for govt polytechnic. Direct admission at private polytechnic colleges.",
    govtJobs: "Junior Engineer PWD, BSEB Technician, NHAI Site Supervisor, BSSC Technical Staff, ITI Instructor (after experience)",
    topColleges: ["Govt Polytechnic Patna", "Govt Polytechnic Muzaffarpur", "Govt Polytechnic Bhagalpur", "Govt Polytechnic Ara", "Govt Polytechnic Gaya"],
    highlights: ["Only 10th pass needed — entry at early age", "B.Tech lateral entry in 2nd year after diploma", "Government polytechnic fees ₹5,000–15,000/yr", "BSCC loan available"],
  },
  {
    name: "ITI",
    full: "Industrial Training Institute",
    duration: "1–2 Years (varies by trade)",
    eligibility: "8th/10th Pass depending on trade. No upper age limit for most trades",
    fee: "₹15,000/yr (Government ITI is near free)",
    careerScope: "Electrician, Fitter, Welder, Plumber, AC Mechanic, Computer Operator in Industries, Railways, Defence, and Private sector. ITI certificate holders get direct railway apprenticeship and factory jobs. Self-employment through workshops also common.",
    mode: "Regular mode from DGT (Directorate General of Training) affiliated government and private ITI colleges. Hostel and BSCC facilities available at select colleges.",
    bscc: true,
    hindiDesc: "ITI 1–2 साल का vocational training course है जो 8th/10th के बाद किया जा सकता है। Electrician, Fitter, Welder, Computer Operator — कई trades हैं। Railway apprenticeship और factory jobs सीधे मिलती हैं। Government ITI में fees लगभग free है। खुद का workshop खोलकर भी अच्छी कमाई होती है।",
    salary: "₹12,000–₹35,000/month (Railway/Factory) | Self-employment higher",
    entranceExam: "Bihar ITI CAT (for govt ITI). Direct admission at private ITI. Very low competition.",
    govtJobs: "Railway Apprentice (RRB), BSEB Electrician, PWD Technical Staff, Defence Tradesman, CISF/BSF Technical Post",
    topColleges: ["Govt ITI Patna", "Govt ITI Muzaffarpur", "Govt ITI Purnia", "Govt ITI Araria", "Govt ITI Bhagalpur"],
    highlights: ["8th/10th pass enough — earliest career start", "Railway apprenticeship after ITI", "Govt ITI fees almost FREE", "Self-employment / workshop possible after course"],
  },
  {
    name: "BCA",
    full: "Bachelor of Computer Applications",
    duration: "3 Years",
    eligibility: "12th Pass (any stream, preferably with Maths or Computer Science). Minimum 45% marks",
    fee: "₹40,000/yr",
    careerScope: "Software Developer, Web Designer, Database Administrator, IT Support Engineer, App Developer. BCA graduates can join MCA (2 years) or directly apply to IT companies like Infosys, TCS, Wipro. High demand in Bihar's growing IT sector.",
    mode: "Regular & Distance modes available from AICTE/UGC-approved universities. Distance BCA from IGNOU and state universities is widely recognized for government jobs too.",
    bscc: true,
    hindiDesc: "BCA computer science का 3 साल का bachelor degree है जो 12th के बाद किया जाता है। Software Developer, Web Designer, App Developer बनने का सबसे affordable रास्ता। TCS, Infosys, Wipro जैसी IT companies में placement मिलती है। MCA करके career और आगे बढ़ा सकते हैं। BSCC loan से fees cover होती है।",
    salary: "₹18,000–₹60,000/month (IT Companies / Fresher to Senior)",
    entranceExam: "No entrance exam. Direct admission based on 12th marks. Maths preferred but not mandatory at all colleges.",
    govtJobs: "SSC CGL (Data Entry/DEO), IBPS IT Officer, State PSC Computer Operator, NIC Junior Engineer, Bank IT Officer",
    topColleges: ["Chandragupt Institute (Patna)", "Patna University", "BNMU Madhepura", "IGNOU (Distance)", "Amity University (Distance)"],
    highlights: ["No NEET, no JEE — direct admission", "MCA possible after BCA for higher salary", "IT companies: TCS, Wipro campus hiring", "BSCC loan up to ₹4 Lakh available"],
  },
  {
    name: "MCA",
    full: "Master of Computer Applications",
    duration: "2 Years",
    eligibility: "BCA / B.Sc (Computer Science / IT / Maths) with minimum 50% marks",
    fee: "₹55,000/yr",
    careerScope: "Senior Software Developer, System Analyst, Project Manager, Cybersecurity Specialist, IT Consultant. MCA qualifies for SSC (CPO/CGL), IBPS IT Officer, and State PSC technical posts. Excellent placement in top IT companies.",
    mode: "Regular & Distance modes from AICTE-approved universities. NIMCET for NIT admissions. We assist with both state universities and top private college admissions.",
    bscc: false,
    hindiDesc: "MCA computer science की master degree है — BCA के बाद 2 साल का यह course Senior Developer, System Analyst, या Project Manager बनाता है। SSC CGL, IBPS IT Officer, और State PSC technical posts के लिए भी eligible होते हैं। Top IT companies में excellent placement और high salary package मिलता है।",
    salary: "₹35,000–₹1,20,000/month (Senior IT roles / MNCs)",
    entranceExam: "NIMCET (for NIT MCA). State-level entrance or direct admission at private universities.",
    govtJobs: "NIC Senior Technical Director, IBPS IT Officer, SSC CGL (Comp. Science), State PSC Technical Officer, BPSC IT Post",
    topColleges: ["NIT Patna (NIMCET)", "Patna University", "Chandragupt Institute", "IGNOU (Distance)", "Sikkim Manipal University (Distance)"],
    highlights: ["2 years after BCA — fast master degree", "Highest IT salary among short courses", "Govt IT officer via IBPS/SSC/State PSC", "NIMCET for NIT — prestigious option"],
  },
  {
    name: "BBA",
    full: "Bachelor of Business Administration",
    duration: "3 Years",
    eligibility: "12th Pass (any stream) with minimum 45% marks from recognized board",
    fee: "₹35,000/yr",
    careerScope: "Business Manager, Marketing Executive, HR Officer, Sales Manager, Entrepreneur, Bank Officer (IBPS PO/Clerk). BBA is the ideal foundation for MBA. Graduates are hired by banks, FMCG companies, and retail chains across India.",
    mode: "Regular & Distance modes available. Distance BBA from recognized universities like IGNOU, SMU, Amity is valid for government and private sector jobs. BSCC loan available.",
    bscc: true,
    hindiDesc: "BBA business management का 3 साल का degree course है। Marketing, HR, Finance, या Sales में career शुरू करें। Bank Officer (IBPS PO) बनने की तैयारी के साथ-साथ करें। MBA के लिए सबसे मजबूत foundation BBA से ही आती है। Companies, banks, और startups सभी BBA graduates hire करते हैं।",
    salary: "₹15,000–₹40,000/month (Marketing/Sales/HR fresher) | Higher after MBA",
    entranceExam: "No entrance exam. Direct admission based on 12th marks at most colleges.",
    govtJobs: "Bank Officer (IBPS PO/Clerk after BBA), SSC CGL (Administrative), State PSC (Commerce), LIC/GIC Officer",
    topColleges: ["Chandragupt Institute (Patna)", "Patna University Commerce Dept", "Amity University (Distance)", "IGNOU (Distance BBA)", "MIT College Muzaffarpur"],
    highlights: ["Best foundation for MBA after 3 years", "IBPS PO/Clerk bank recruitment open to BBA", "No entrance exam — easy admission", "BSCC loan available"],
  },
  {
    name: "MBA",
    full: "Master of Business Administration",
    duration: "2 Years",
    eligibility: "Graduation (any stream) with minimum 50% marks. CAT/MAT/CMAT scores for premium institutes",
    fee: "₹70,000–3 Lakh/yr (varies widely)",
    careerScope: "Operations Manager, Finance Manager, Marketing Head, HR Director, Startup CEO, IAS/IPS (Civil Services). MBA from AICTE-approved college is a top credential for corporate and government leadership roles.",
    mode: "Regular & Distance modes available. Regular MBA for premium placements; Distance MBA from UGC-DEB approved universities valid for government jobs. We guide for both entrance and direct admission routes.",
    bscc: false,
    hindiDesc: "MBA management की master degree है — business world में सबसे respected qualification। Graduation के बाद CAT/MAT/CMAT देकर top B-School में admission पाएं। Finance Manager, Marketing Head, HR Director, या खुद का business — सब कुछ MBA से possible है। Government leadership roles के लिए भी MBA बहुत काम आती है।",
    salary: "₹40,000–₹2,00,000/month (Top B-School MBA / MNC Manager)",
    entranceExam: "CAT (IIM), MAT, CMAT, XAT, NMAT. Direct admission at many private colleges without entrance.",
    govtJobs: "State PSC (Management Officer), Bank PO (IBPS), LIC AAO, NABARD Officer, Public Sector Manager (PSU)",
    topColleges: ["IIM Bodh Gaya (Bihar)", "Chandragupt Institute of Management (Patna)", "Birla Institute (Pilani)", "XLRI Jamshedpur", "IMT Ghaziabad"],
    highlights: ["IIM Bodh Gaya is in Bihar — local option", "CAT score opens IIM & top B-Schools", "PSU management jobs via GATE/PSC", "Highest ROI among all management courses"],
  },
];

export const paramedicalCourses: Course[] = [
  {
    name: "B.P.T",
    full: "Bachelor of Physiotherapy",
    duration: "4 Years + 6 Month Internship",
    eligibility: "10+2 with Biology (PCB), minimum 45% marks",
    fee: "₹75,000/yr (Total ~₹4,00,000)",
    careerScope: "Physiotherapist in Government & Private Hospitals, Sports Rehabilitation Centers, Fitness Clinics, Home Care Therapy. Growing demand in corporate wellness, sports injury management, and elderly care. NHM, ESIC, Railway hire BPT graduates.",
    mode: "Regular mode from university-approved colleges. Practical clinical training included in teaching hospitals.",
    bscc: true,
    hindiDesc: "B.P.T Physiotherapy का 4.5 साल का degree course है। Hospital में Physiotherapist बनें, Sports clinic खोलें, या Home care therapy शुरू करें। NHM, ESIC, और Railway में government jobs मिलती हैं। BSCC loan से fees cover होती है।",
    salary: "₹20,000–₹60,000/month (Govt Physiotherapist / Private Clinic)",
    entranceExam: "No NEET required. State-level entrance or direct admission based on PCB marks.",
    govtJobs: "NHM Physiotherapist, ESIC Physio, Railway Hospital Physio, AIIMS, Defence Rehabilitation Center",
    topColleges: ["Para Medical colleges Patna", "IGIMS Patna", "Ranchi Institute of Para Medical Sciences", "MP Para Medical colleges", "BPT colleges Jharkhand"],
    highlights: ["No NEET required — PCB 12th enough", "Growing demand in sports & rehabilitation", "Govt jobs in AIIMS, Railway, ESIC", "BSCC loan up to ₹4 Lakh available"],
  },
  {
    name: "B.O.T.T",
    full: "Bachelor of Operation Theatre Technology",
    duration: "4 Years + 6 Month Internship",
    eligibility: "10+2 with Biology (PCB), minimum 45% marks",
    fee: "₹75,000/yr (Total ~₹4,00,000)",
    careerScope: "Operation Theatre Technician in Government & Private Hospitals, Surgical Centers, AIIMS, ESIC. OT Technicians assist surgeons during operations — highly specialized and in-demand role across Bihar and India.",
    mode: "Regular mode from approved para medical colleges. OT lab practical training in partner hospitals.",
    bscc: true,
    hindiDesc: "B.O.T.T Operation Theatre Technology का 4.5 साल का degree course है। Surgery के दौरान OT technician की बहुत जरूरत होती है। Government और private hospitals में अच्छी job मिलती है। BSCC loan available है।",
    salary: "₹18,000–₹50,000/month (OT Technician in Govt/Private Hospital)",
    entranceExam: "No NEET required. Direct admission based on 12th PCB marks.",
    govtJobs: "Govt Hospital OT Tech, AIIMS OT Technician, ESIC OT Staff, Railway Hospital, Defence Medical Corps",
    topColleges: ["Para Medical colleges Patna", "IGIMS Patna", "Ranchi RIMS", "MP Para Medical colleges", "Jharkhand approved colleges"],
    highlights: ["Specialized role assisting surgeons in OT", "Govt jobs in AIIMS, ESIC, Railway", "Less competition than Nursing/BPT", "BSCC loan up to ₹4 Lakh"],
  },
  {
    name: "B.R.I.T",
    full: "Bachelor of Radio Imaging Technology",
    duration: "4 Years + 6 Month Internship",
    eligibility: "10+2 with Biology (PCB), minimum 45% marks",
    fee: "₹50,000/yr (Total ~₹2,00,000)",
    careerScope: "Radiology Technician operating X-Ray, MRI, CT Scan, Ultrasound in hospitals. Every major hospital needs Radio Imaging Technicians. High demand in diagnostic centers, government hospitals, and private radiology labs.",
    mode: "Regular mode from approved para medical colleges. Imaging lab practical training included.",
    bscc: true,
    hindiDesc: "B.R.I.T Radio Imaging Technology का course है — X-Ray, MRI, CT Scan operate करना सीखें। हर hospital को radiology technician चाहिए। Government और private diagnostic centers में अच्छी salary मिलती है। BSCC loan से fees cover होती है।",
    salary: "₹15,000–₹45,000/month (Radiology Tech in Govt/Private)",
    entranceExam: "No NEET required. Direct admission based on 12th PCB marks.",
    govtJobs: "Govt Hospital X-Ray Tech, ESIC Radiology Tech, Railway Radiographer, NHM Imaging Tech, AIIMS Technician",
    topColleges: ["Para Medical colleges Patna", "PMCH Allied Health Dept", "Ranchi Para Medical Institute", "MP approved colleges", "WB colleges for BRIT"],
    highlights: ["X-Ray, MRI, CT Scan operator — high demand", "Every hospital needs BRIT graduates", "Govt recruitment under NHM & ESIC", "BSCC loan available"],
  },
  {
    name: "B.M.L.T",
    full: "Bachelor of Medical Lab Technology",
    duration: "3 Years + 1 Year Internship",
    eligibility: "10+2 with Biology (PCB), minimum 45% marks",
    fee: "₹50,000/yr (Total ~₹2,05,000)",
    careerScope: "Medical Lab Technician in Govt & Private Hospitals, Diagnostic Centers, Blood Banks, Pathology Labs. BMLT graduates work in AIIMS, ESIC, Railway hospitals. Gulf and UK job opportunities. High demand in Bihar's growing diagnostic sector.",
    mode: "Regular mode from approved para medical colleges. Clinical lab internship in teaching hospitals.",
    bscc: true,
    hindiDesc: "B.M.L.T medical lab technology का 4 साल का degree course है। Blood tests, pathology — इन सब में expert बनें। AIIMS, ESIC जैसे top government hospitals में Lab Technician की नौकरी मिलती है। BSCC loan available।",
    salary: "₹18,000–₹45,000/month (Govt Lab Technician / Private Diagnostic)",
    entranceExam: "No NEET required. Direct admission based on PCB 12th marks.",
    govtJobs: "AIIMS Lab Tech, ESIC Medical Lab Tech, Railway Lab Tech, NHM Lab Technician, State Hospital Lab",
    topColleges: ["PMCH Patna (Govt)", "IGIMS Patna", "AIIMS Patna", "SKMCH Muzaffarpur", "Private colleges Bihar & Jharkhand"],
    highlights: ["Growing demand in diagnostic sector", "Govt jobs in AIIMS, Railway, ESIC", "Gulf/UK job opportunities", "BSCC loan available"],
  },
  {
    name: "B.O.T",
    full: "Bachelor of Occupational Therapy",
    duration: "4 Years + 6 Month Internship",
    eligibility: "10+2 with Biology (PCB), minimum 45% marks",
    fee: "₹50,000/yr (Total ~₹2,00,000)",
    careerScope: "Occupational Therapist in rehabilitation centers, hospitals, schools for special needs children, community health programs. Growing demand with aging population and disability programs. ESIC and NHM hire OT graduates.",
    mode: "Regular mode from approved para medical colleges. Rehabilitation center training included.",
    bscc: true,
    hindiDesc: "B.O.T Occupational Therapy का course है — differently-abled और rehabilitation patients की daily activities में मदद करना सीखें। NHM, ESIC में government positions हैं। BSCC loan available।",
    salary: "₹18,000–₹45,000/month (OT in Rehab Center / Hospital)",
    entranceExam: "No NEET required. Direct admission based on PCB marks.",
    govtJobs: "NHM OT Staff, ESIC Occupational Therapist, Govt Rehabilitation Center, Disability Welfare Dept",
    topColleges: ["IGIMS Patna", "Para Medical colleges Bihar", "Ranchi Institute of Para Medical", "MP approved OT colleges", "WB colleges"],
    highlights: ["Rehabilitation & special needs care career", "Govt positions in NHM and ESIC", "Community health programs demand OTs", "BSCC loan available"],
  },
  {
    name: "B.Sc. Biotech",
    full: "Bachelor of Science in Biotechnology",
    duration: "3 Years",
    eligibility: "10+2 with Biology (PCB), minimum 45% marks",
    fee: "₹1,18,100 (1st Yr) + ₹99,500 (2nd Yr) + ₹19,500 (3rd Yr) ≈ ₹2,38,000 total",
    careerScope: "Biotechnology Research Assistant, Quality Control Officer in Pharma companies, Lab Technician in biotech firms, Research in CSIR/ICAR. Rising opportunities in biotech startups, agri-biotech and healthcare biotech sectors.",
    mode: "Regular mode from UGC-approved universities. Research and lab-based practical training included.",
    bscc: true,
    hindiDesc: "B.Sc. Biotechnology modern science का exciting course है। Pharma companies, research labs, और biotech startups में career बनाएं। MSc और PhD करके scientist बनें। CSIR, ICAR जैसे government research institutes में भी opportunities हैं। BSCC loan available।",
    salary: "₹15,000–₹40,000/month (Pharma/Biotech fresher) | Higher after MSc",
    entranceExam: "No NEET required. University entrance or direct admission based on PCB marks.",
    govtJobs: "CSIR Research Assistant, ICAR Field Scientist, Pharma Quality Control (PSU), NHM Lab, DRDO Technical Staff",
    topColleges: ["BIT Mesra Ranchi", "Patna University", "Nalanda University", "Bangalore Biotech colleges", "IP University Delhi"],
    highlights: ["Research and pharma career path", "MSc/PhD possible for higher roles", "CSIR & ICAR Govt research jobs", "BSCC loan available"],
  },
  {
    name: "Hospital Mgmt",
    full: "B.Sc. in Hospital Management",
    duration: "3 Years + 1 Year Internship",
    eligibility: "10+2 (any stream), minimum 45% marks",
    fee: "₹1,00,000/yr (Total ~₹4,00,000 with hostel)",
    careerScope: "Hospital Administrator, Healthcare Manager, Patient Relations Officer, Medical Records Manager, Operations Manager. Growing demand as private hospitals expand rapidly across Bihar. MHA (Master of Hospital Administration) possible after this degree.",
    mode: "Regular mode from approved university colleges. Hospital internship included in top teaching hospitals.",
    bscc: true,
    hindiDesc: "Hospital Management का course hospital को manage करना सिखाता है। Private hospitals की बढ़ती संख्या के साथ Healthcare Manager की बहुत demand है। 12th किसी भी stream से कर सकते हैं। BSCC loan से fees cover होती है।",
    salary: "₹20,000–₹60,000/month (Hospital Admin / Healthcare Manager)",
    entranceExam: "No entrance exam. Direct admission based on 12th marks (any stream).",
    govtJobs: "Govt Hospital Admin Staff, NHM Management Officer, ESIC Hospital Manager, AIIMS Administration",
    topColleges: ["IGIMS Patna", "Hospital Mgmt colleges Bihar", "Bangalore management colleges", "IIHMR Jaipur", "Manipal College of Health Professions"],
    highlights: ["Any stream 12th eligible — no biology required", "Growing private hospital sector in Bihar", "MHA (Masters) possible for higher roles", "BSCC loan available"],
  },
  {
    name: "D.M.L.T",
    full: "Diploma in Medical Lab Technology",
    duration: "2 Years",
    eligibility: "10+2 with Biology (ISc/PCB), minimum 40% marks",
    fee: "₹30,000/yr (Total ₹60,000)",
    careerScope: "Medical Lab Technician (diploma level) in Private Diagnostic Centers, Clinics, Community Health Centers. Quick and affordable route to Lab Tech career. Can upgrade to BMLT degree later.",
    mode: "Regular mode from approved para medical institutions. Short duration and low cost.",
    bscc: true,
    hindiDesc: "D.M.L.T Medical Lab Technology का 2 साल का diploma है। कम fees में Lab Technician बनें और diagnostic centers में काम करें। बाद में BMLT (degree) करके career upgrade कर सकते हैं। BSCC loan available।",
    salary: "₹10,000–₹25,000/month (Private Lab / Clinic / NHM)",
    entranceExam: "No entrance exam. Direct admission based on 12th Biology marks.",
    govtJobs: "NHM Lab Tech, PHC Lab Technician, Community Health Center Lab",
    topColleges: ["Para Medical colleges Patna", "District-level approved institutions Bihar", "Jharkhand DMLT colleges", "MP para medical colleges"],
    highlights: ["2 years — quick career start", "Low total fees ₹60,000", "Can upgrade to BMLT degree later", "BSCC loan available"],
  },
  {
    name: "D.O.T.A",
    full: "Diploma in Operation Theatre Assistant",
    duration: "2 Years",
    eligibility: "10+2 with Biology (ISc/PCB), minimum 40% marks",
    fee: "₹30,000/yr (Total ₹60,000)",
    careerScope: "OT Assistant in Government & Private Hospitals, Nursing Homes, Surgical Centers. Works under OT Technicians and surgeons. Entry-level hospital role with career growth path to BOTT degree.",
    mode: "Regular mode from approved para medical institutions.",
    bscc: true,
    hindiDesc: "D.O.T.A Operation Theatre Assistant का 2 साल का diploma है। Hospital में OT में surgery support करें। कम fees में hospital job का रास्ता। BOTT degree करके career आगे बढ़ा सकते हैं। BSCC loan available।",
    salary: "₹10,000–₹22,000/month (OT Assistant in Hospital)",
    entranceExam: "No entrance exam. Direct admission based on 12th marks.",
    govtJobs: "Govt Hospital OT Assistant, NHM, PHC/CHC Surgery Support Staff",
    topColleges: ["Para Medical colleges Patna", "Bihar approved diploma institutions", "Ranchi para medical colleges"],
    highlights: ["2 year diploma — quick entry into OT work", "Low total fees ₹60,000", "Can upgrade to BOTT degree later", "BSCC loan available"],
  },
  {
    name: "D.M.R (X-Ray)",
    full: "Diploma in Medical Radiology",
    duration: "2 Years",
    eligibility: "10+2 with Biology (ISc/PCB), minimum 40% marks",
    fee: "₹30,000/yr (Total ₹60,000)",
    careerScope: "X-Ray Technician in Clinics, Diagnostic Centers, Government Health Programs. Quick and affordable route to radiology career. Can upgrade to BRIT degree later for higher roles.",
    mode: "Regular mode from approved para medical institutions.",
    bscc: true,
    hindiDesc: "D.M.R (X-Ray) Diploma में X-Ray machine operate करना सीखें। 2 साल में X-Ray Technician बनें। Diagnostic centers और government hospitals में job मिलती है। BRIT degree करके career grow कर सकते हैं। BSCC loan available।",
    salary: "₹10,000–₹22,000/month (X-Ray Tech in Clinic/Hospital)",
    entranceExam: "No entrance exam. Direct admission based on 12th Biology marks.",
    govtJobs: "NHM X-Ray Tech, PHC Radiographer, Govt Hospital Radiology Dept",
    topColleges: ["Para Medical colleges Bihar", "District hospital affiliated colleges", "Jharkhand para medical institutions"],
    highlights: ["2 years — fastest X-Ray tech career", "Low total fees ₹60,000", "NHM recruits DMR holders", "BSCC loan available"],
  },
  {
    name: "O.P.T",
    full: "Ophthalmic Para Medical Technician",
    duration: "3 Years",
    eligibility: "10+2 with Biology (ISc/PCB), minimum 40% marks",
    fee: "₹30,000/yr (Total ₹90,000)",
    careerScope: "Eye Care Technician in Eye Hospitals, Vision Centers, Government Health Programs. National Blindness Control Program (NPCB) hires OPT graduates. Bihar's eye care sector is growing rapidly.",
    mode: "Regular mode from approved eye care institutions. Practical training in eye hospitals included.",
    bscc: true,
    hindiDesc: "O.P.T Eye Care Technician बनने का 3 साल का diploma है। Eye hospitals और vision centers में काम करें। NPCB के तहत government jobs मिलती हैं। BSCC loan available।",
    salary: "₹10,000–₹25,000/month (Eye Care Tech in Hospital/Clinic)",
    entranceExam: "No entrance exam. Direct admission based on 12th marks.",
    govtJobs: "NPCB Eye Tech, Govt Eye Hospital Staff, PHC Eye Care Worker, NHM Vision Program",
    topColleges: ["Eye care institutions Patna", "Bihar approved OPT colleges", "Regional eye care training centers"],
    highlights: ["Eye care — growing health sector", "NPCB govt program jobs available", "3 years — affordable career path", "BSCC loan available"],
  },
  {
    name: "O.F.C.G",
    full: "Orthotics, Footwear Correction & Gait",
    duration: "3 Years",
    eligibility: "10+2 with Biology (ISc/PCB), minimum 40% marks",
    fee: "₹30,000/yr (Total ₹90,000)",
    careerScope: "Orthotist / Prosthetics Technician in rehabilitation centers, disability welfare programs, hospitals. Government ALIMCO and disability welfare departments hire OFCG graduates. Niche but highly specialized skill with stable demand.",
    mode: "Regular mode from approved para medical institutions.",
    bscc: true,
    hindiDesc: "O.F.C.G Orthotics का 3 साल का diploma है। Disabled patients के लिए artificial limbs और footwear correction devices बनाना सीखें। ALIMCO (Govt) और disability welfare centers में jobs मिलती हैं। BSCC loan available।",
    salary: "₹12,000–₹30,000/month (Orthotist / Prosthetics Tech)",
    entranceExam: "No entrance exam. Direct admission based on 12th marks.",
    govtJobs: "ALIMCO Orthotist, Disability Welfare Dept, NHM Rehabilitation Tech, Govt Hospital Orthotics",
    topColleges: ["Para Medical colleges Bihar", "NIOH Kolkata affiliated colleges", "Approved institutions Jharkhand"],
    highlights: ["Niche specialization — less competition", "ALIMCO govt jobs available", "Disability rehabilitation — meaningful career", "BSCC loan available"],
  },
  {
    name: "Dresser",
    full: "Dresser (Wound Dressing Technician)",
    duration: "1 Year",
    eligibility: "10th Pass from recognized board",
    fee: "₹50,950 (total, 1 year)",
    careerScope: "Wound Dresser in Government & Private Hospitals, PHCs, CHCs, Nursing Homes. Entry-level healthcare role with steady government job opportunities in Bihar's Primary Health Centers.",
    mode: "Regular mode from approved para medical training centers. 1 year practical hands-on training.",
    bscc: false,
    hindiDesc: "Dresser course 1 साल का है और सिर्फ 10th pass होना जरूरी है। Hospital में wound dressing करना सीखें। PHC, CHC, और government hospitals में नौकरी मिलती है। Healthcare sector में सबसे किफायती और तेज entry का तरीका।",
    salary: "₹8,000–₹18,000/month (Hospital Dresser / PHC Staff)",
    entranceExam: "No entrance exam. Direct admission based on 10th marks.",
    govtJobs: "PHC/CHC Dresser, NHM Health Staff, Govt Hospital Wound Care Staff",
    topColleges: ["Para Medical training centers Bihar", "District hospital training programs", "Approved private para medical institutions"],
    highlights: ["Only 10th pass needed — earliest entry", "1 year — fastest healthcare job", "PHC/CHC govt recruitment available", "Most affordable para medical course"],
  },
];

export const lawCourses: Course[] = [
  {
    name: "LLB",
    full: "Bachelor of Laws",
    duration: "3 Years",
    eligibility: "Graduation (any stream) pass from recognized university",
    fee: "₹60,000/yr (Total ~₹1,80,000; with hostel ~₹3,95,000)",
    careerScope: "Advocate in Courts, Corporate Legal Officer, Government Legal Advisor, Notary, Judicial Magistrate via Bihar Judicial Services. LLB also opens Civil Services (law optional), State PSC legal posts, and High Court Advocate roles.",
    mode: "Regular mode from BCI (Bar Council of India) approved law colleges. We guide for admissions across Bihar, Jharkhand and UP.",
    bscc: true,
    hindiDesc: "LLB 3 साल का law degree है जो graduation के बाद होता है। Advocate बनें, court में cases लड़ें, या government legal officer बनें। Bihar Judicial Services से Civil Judge बन सकते हैं। BSCC loan से fees cover होती है।",
    salary: "₹25,000–₹1,50,000/month (Advocate / Govt Legal Officer / Judge)",
    entranceExam: "CLAT (for NLU colleges). State-level entrance or direct admission at private law colleges.",
    govtJobs: "Bihar Judicial Services (Civil Judge), Government Pleader, Public Prosecutor, Legal Aid Officer, State PSC Legal Post",
    topColleges: ["Patna Law College (Patna University)", "Chanakya National Law University Patna", "Law colleges Muzaffarpur & Bhagalpur", "HNLU Raipur", "CNLU Patna"],
    highlights: ["Graduation in any stream eligible", "Civil Judge via Bihar Judicial Services", "BSCC loan up to ₹4 Lakh available", "Most respected profession — Advocate / Judge"],
  },
  {
    name: "BA.LLB",
    full: "Bachelor of Arts & Laws (Integrated)",
    duration: "5 Years",
    eligibility: "10+2 (any stream), minimum 45% marks from recognized board",
    fee: "₹60,000/yr (Total ~₹3,00,000)",
    careerScope: "Integrated law degree after 12th — no separate graduation needed. Advocate, Corporate Lawyer, Civil Services (law optional), High Court practice. Eligible for Bihar Judicial Services after degree.",
    mode: "Regular mode from BCI-approved 5-year law colleges. We guide for CLAT and direct admission routes.",
    bscc: true,
    hindiDesc: "BA.LLB 5 साल का integrated law course है जो 12th के बाद शुरू होता है। अलग से graduation करने की जरूरत नहीं। 5 साल में lawyer बनें। Bihar में law career के लिए सबसे popular choice। BSCC loan available।",
    salary: "₹25,000–₹1,50,000/month (Advocate / Corporate Lawyer / Judge)",
    entranceExam: "CLAT (for NLU/top law colleges). Direct admission at private BCI-approved colleges.",
    govtJobs: "Bihar Judicial Services, Public Prosecutor, Govt Legal Advisor, State PSC Law Officer, Legal Aid",
    topColleges: ["CNLU Patna (via CLAT)", "Chanakya Law University Patna", "HNLU Raipur", "NLU Jodhpur", "Private law colleges Patna & Muzaffarpur"],
    highlights: ["Start after 12th — no separate graduation needed", "5-year integrated degree", "CLAT for NLU admission", "BSCC loan available"],
  },
  {
    name: "BBA.LLB",
    full: "Bachelor of Business Administration & Laws",
    duration: "5 Years",
    eligibility: "10+2 (any stream), minimum 45% marks from recognized board",
    fee: "₹60,000/yr (Total ~₹3,00,000)",
    careerScope: "Corporate Lawyer, Business Legal Advisor, Company Secretary complement, Contract Law Specialist. Ideal for students wanting to combine business and legal knowledge. High-paying roles in MNCs, startups, and business law firms.",
    mode: "Regular mode from BCI-approved law colleges with integrated management curriculum.",
    bscc: true,
    hindiDesc: "BBA.LLB 5 साल का integrated course है जिसमें Business और Law दोनों की पढ़ाई होती है। Corporate law firms और MNCs में high-paying jobs मिलती हैं। 12th के बाद सीधे शुरू करें। BSCC loan available।",
    salary: "₹30,000–₹2,00,000/month (Corporate Lawyer / Legal Advisor MNC)",
    entranceExam: "CLAT (for NLU BBA.LLB). Direct admission at private BCI-approved colleges.",
    govtJobs: "Govt Legal Advisor, PSU Legal Officer, State PSC Law Officer, Regulatory Body Legal Counsel",
    topColleges: ["CNLU Patna (via CLAT)", "Chanakya Law University", "HNLU Raipur", "Private law colleges Patna", "Amity Law School"],
    highlights: ["Business + Law combined — corporate career", "High salary in MNC legal departments", "Start after 12th — integrated 5-year", "BSCC loan available"],
  },
  {
    name: "LLM",
    full: "Master of Laws",
    duration: "2 Years",
    eligibility: "LLB (3-yr) or BA.LLB / BBA.LLB (5-yr) pass with minimum 45% marks",
    fee: "₹60,000/yr (Total ₹1,20,000; with hostel ~₹3,00,000)",
    careerScope: "Senior Advocate (High Court / Supreme Court), Law Professor (UGC-NET), Judicial Magistrate (fast-track), Specialized Legal Consultant in IPR, Tax, Constitutional Law. LLM required for law faculty positions at universities.",
    mode: "Regular & Distance modes from BCI-approved and UGC-recognized law universities.",
    bscc: false,
    hindiDesc: "LLM Law की master degree है। LLB के बाद 2 साल का यह course करके Senior Advocate, Law Professor, या Judicial Magistrate बन सकते हैं। UGC-NET qualify करके law college में faculty position मिलती है।",
    salary: "₹50,000–₹3,00,000/month (Senior Advocate / Law Professor / HC Judge)",
    entranceExam: "University-level entrance or merit-based. UGC-NET required for law faculty post after LLM.",
    govtJobs: "Law University Faculty (UGC-NET), Bihar Higher Judicial Services, High Court Advocate, Govt Senior Legal Counsel",
    topColleges: ["Patna Law College", "CNLU Patna", "BHU Law Faculty Varanasi", "HNLU Raipur", "NALSAR Hyderabad"],
    highlights: ["Highest law degree — opens Senior Advocate path", "UGC-NET → Law Professor career", "High Court / Supreme Court practice possible", "Fastest track to senior judicial roles"],
  },
];

export type StreamKey = "teaching" | "medical" | "paramedical" | "law" | "technical";

export const streamTabs: { key: StreamKey; label: string; shortLabel: string; icon: typeof GraduationCap; color: string; courses: Course[] }[] = [
  { key: "teaching",    label: "Teaching Courses",      shortLabel: "Teaching",   icon: GraduationCap, color: "blue",   courses: teachingCourses },
  { key: "medical",     label: "Medical & Nursing",      shortLabel: "Medical",    icon: Stethoscope,   color: "red",    courses: medicalCourses },
  { key: "paramedical", label: "Para Medical",           shortLabel: "Para Med",   icon: Activity,      color: "green",  courses: paramedicalCourses },
  { key: "law",         label: "Law Courses",            shortLabel: "Law",        icon: Scale,         color: "amber",  courses: lawCourses },
  { key: "technical",   label: "Technical & Management", shortLabel: "Technical",  icon: Cpu,           color: "orange", courses: technicalCourses },
];

export const colorMap: Record<string, {
  tab: string; active: string; badge: string; btn: string; card: string; icon: string;
  gradient: string; accentBar: string; sectionBg: string; shadow: string;
  pointBorder: string; pointText: string; checkColor: string;
}> = {
  blue: {
    tab: "text-blue-700 border-blue-600 bg-blue-50",
    active: "bg-blue-600",
    badge: "bg-blue-100 text-blue-700",
    btn: "bg-blue-600 hover:bg-blue-700",
    card: "hover:border-blue-300",
    icon: "bg-blue-100 text-blue-600",
    gradient: "from-blue-600 to-indigo-700",
    accentBar: "from-blue-500 to-indigo-500",
    sectionBg: "bg-blue-50/40",
    shadow: "shadow-blue-200",
    pointBorder: "border-blue-100",
    pointText: "text-blue-800",
    checkColor: "text-blue-500",
  },
  red: {
    tab: "text-red-700 border-red-600 bg-red-50",
    active: "bg-red-600",
    badge: "bg-red-100 text-red-700",
    btn: "bg-red-600 hover:bg-red-700",
    card: "hover:border-red-300",
    icon: "bg-red-100 text-red-600",
    gradient: "from-red-600 to-rose-700",
    accentBar: "from-red-500 to-rose-500",
    sectionBg: "bg-red-50/40",
    shadow: "shadow-red-200",
    pointBorder: "border-red-100",
    pointText: "text-red-800",
    checkColor: "text-red-500",
  },
  green: {
    tab: "text-green-700 border-green-600 bg-green-50",
    active: "bg-green-600",
    badge: "bg-green-100 text-green-700",
    btn: "bg-green-600 hover:bg-green-700",
    card: "hover:border-green-300",
    icon: "bg-green-100 text-green-600",
    gradient: "from-green-600 to-green-800",
    accentBar: "from-green-500 to-green-700",
    sectionBg: "bg-green-50/40",
    shadow: "shadow-green-200",
    pointBorder: "border-green-100",
    pointText: "text-green-800",
    checkColor: "text-green-500",
  },
  amber: {
    tab: "text-amber-700 border-amber-600 bg-amber-50",
    active: "bg-amber-600",
    badge: "bg-amber-100 text-amber-700",
    btn: "bg-amber-600 hover:bg-amber-700",
    card: "hover:border-amber-300",
    icon: "bg-amber-100 text-amber-600",
    gradient: "from-amber-500 to-orange-600",
    accentBar: "from-amber-400 to-orange-500",
    sectionBg: "bg-amber-50/40",
    shadow: "shadow-amber-200",
    pointBorder: "border-amber-100",
    pointText: "text-amber-800",
    checkColor: "text-amber-500",
  },
  orange: {
    tab: "text-orange-700 border-orange-600 bg-orange-50",
    active: "bg-orange-600",
    badge: "bg-orange-100 text-orange-700",
    btn: "bg-orange-600 hover:bg-orange-700",
    card: "hover:border-orange-300",
    icon: "bg-orange-100 text-orange-600",
    gradient: "from-orange-600 to-amber-600",
    accentBar: "from-orange-500 to-amber-500",
    sectionBg: "bg-orange-50/40",
    shadow: "shadow-orange-200",
    pointBorder: "border-orange-100",
    pointText: "text-orange-800",
    checkColor: "text-orange-500",
  },
};

export const faqs = [
  // ── परामर्श व सेवा ──────────────────────────────────────────
  {
    q: "क्या Siksha Wallah की काउंसलिंग बिल्कुल निःशुल्क है?",
    a: "हाँ, 100% निःशुल्क! पहली काउंसलिंग, प्रोफाइल समीक्षा, कोर्स सुझाव — सब कुछ मुफ्त है। कोई छिपा हुआ शुल्क नहीं, कोई दबाव नहीं। हमारा विश्वास है कि हर छात्र को सही मार्गदर्शन मिलनी चाहिए।",
  },
  {
    q: "Siksha Wallah से कैसे संपर्क करें?",
    a: "आप तीन तरीकों से संपर्क कर सकते हैं: (1) WhatsApp: +91 6203138576 पर मैसेज करें, (2) कॉल: +91 6203138576 पर फोन करें, (3) ऑफिस विजिट: College Chowk, Near HP Petrol Pump, Forbesganj, Araria, Bihar। सोमवार–शनिवार सुबह 9 बजे से शाम 7 बजे तक।",
  },
  {
    q: "Siksha Wallah 2015 से कार्यरत है — क्या यह भरोसेमंद है?",
    a: "बिल्कुल! 11+ साल के अनुभव में हमने 5000+ छात्रों को सफलतापूर्वक admission दिलाई है। हम NCTE, INC, PCI, AICTE approved कॉलेजों के साथ काम करते हैं। हमारी 98% success rate और शून्य छिपे शुल्क की नीति ही हमारी पहचान है।",
  },
  {
    q: "Admission के बाद भी मदद मिलेगी?",
    a: "हाँ! हम पहली जानकारी से लेकर admission पूरा होने तक साथ हैं — दस्तावेज़ सत्यापन, हॉस्टल मार्गदर्शन, कॉलेज विजिट, और admission के बाद की समस्याएँ भी। Siksha Wallah सिर्फ admission नहीं, पूरा सफर है।",
  },

  // ── कोर्स चुनाव ─────────────────────────────────────────────
  {
    q: "12वीं के बाद कौन सा कोर्स करें — B.Ed, Nursing, या B.Tech?",
    a: "यह आपकी stream और लक्ष्य पर निर्भर करता है: • Arts/Science 12th → B.Ed / D.El.Ed (Teaching career के लिए) • Science (PCB) → MBBS, B.Sc Nursing, GNM, B.Pharma (Medical के लिए) • Science (PCM) → B.Tech, Polytechnic (Engineering के लिए) • Commerce/Arts → BBA, BCA, MBA (Management के लिए)। हमसे बात करें — हम आपकी marks और बजट के हिसाब से बेस्ट कोर्स सुझाएंगे।",
  },
  {
    q: "Bihar में सरकारी नौकरी के लिए कौन सा कोर्स सबसे अच्छा है?",
    a: "Bihar में सरकारी नौकरी के लिए शीर्ष कोर्स: (1) B.Ed / D.El.Ed → Bihar STET/BTET पास करके Primary/Secondary Teacher (₹25,000–55,000/माह), (2) MBBS → BPSC Medical Officer (₹1 लाख+/माह), (3) B.Sc Nursing / GNM → NHM/AIIMS Staff Nurse, (4) B.Tech → BPSC/SSC JE Engineer, (5) B.Pharma → Govt Pharmacist। सभी courses के लिए हम BSCC loan guidance भी देते हैं।",
  },
  {
    q: "क्या Distance Mode (दूरस्थ शिक्षा) से B.Ed या BBA करना मान्य है?",
    a: "हाँ! NCTE / UGC-DEB approved universities से Distance B.Ed और Distance BBA/MBA पूरी तरह मान्य है। कई सरकारी नौकरियों में Distance degree स्वीकार की जाती है। IGNOU, Nalanda Open University, और अन्य मान्यताप्राप्त विश्वविद्यालयों से हम गाइड करते हैं।",
  },
  {
    q: "क्या बिना NEET के Medical कोर्स हो सकता है?",
    a: "हाँ! NEET सिर्फ MBBS और BDS के लिए अनिवार्य है। इन कोर्सों के लिए NEET की जरूरत नहीं: B.Sc Nursing, GNM, ANM, B.Pharma, D.Pharma, BMLT। ये सभी 12th Science (PCB) के बाद सीधे admission से हो जाते हैं और सरकारी नौकरी के रास्ते भी खुलते हैं।",
  },
  {
    q: "Polytechnic / ITI करने के बाद क्या B.Tech कर सकते हैं?",
    a: "हाँ! Polytechnic (Diploma in Engineering) के बाद B.Tech के 2nd year में सीधे Lateral Entry मिलती है। यानी 3 साल Polytechnic + 3 साल B.Tech = 6 साल में B.Tech degree। ITI के बाद भी Polytechnic में Lateral Entry संभव है। यह कम खर्च में Engineering degree का सबसे अच्छा रास्ता है।",
  },

  // ── दाखिला प्रक्रिया ─────────────────────────────────────────
  {
    q: "Admission के लिए कौन से दस्तावेज़ चाहिए?",
    a: "आमतौर पर ये दस्तावेज़ चाहिए: ✅ 10वीं मार्कशीट व प्रमाणपत्र, ✅ 12वीं मार्कशीट व प्रमाणपत्र, ✅ Transfer Certificate (TC), ✅ आधार कार्ड, ✅ पासपोर्ट साइज फोटो (6–8), ✅ जाति प्रमाणपत्र (SC/ST/OBC के लिए), ✅ निवास प्रमाणपत्र (Bihar Domicile), ✅ आय प्रमाणपत्र (BSCC के लिए)। MBBS/NEET courses के लिए NEET Scorecard भी चाहिए।",
  },
  {
    q: "Siksha Wallah कौन से राज्यों में Admission करवाता है?",
    a: "हम मुख्यतः Bihar के छात्रों को इन राज्यों के colleges में admission दिलाते हैं: Bihar (Patna, Purnea, Katihar, Araria), West Bengal (Nursing colleges), Madhya Pradesh (Pharmacy colleges), Jharkhand, Uttar Pradesh, और अन्य राज्य। Teaching courses के लिए NCTE Approved, Medical के लिए INC/PCI Approved, Technical के लिए AICTE Approved colleges।",
  },
  {
    q: "क्या Hostel की सुविधा मिलती है?",
    a: "हाँ! हमारे partner colleges में Boys और Girls दोनों के लिए Hostel उपलब्ध है। Hostel fees BSCC loan में cover होती है। हम hostel allocation, mess facility, और hostel नियमों के बारे में पूरी जानकारी admission से पहले देते हैं।",
  },

  // ── BSCC लोन ─────────────────────────────────────────────────
  {
    q: "Bihar Student Credit Card (BSCC) क्या है और कितना loan मिलता है?",
    a: "BSCC बिहार सरकार की योजना है जिसमें 12वीं पास छात्रों को उच्च शिक्षा के लिए ₹4 लाख तक का loan मात्र 4% ब्याज दर पर मिलता है। Loan में Tuition fees, Hostel fees, खाना, किताबें, Laptop सब cover होता है। 25 साल तक की उम्र के Bihar के छात्र जिनके परिवार की वार्षिक आय ₹4.5 लाख से कम है, वे eligible हैं।",
  },
  {
    q: "BSCC Loan के लिए कौन से documents चाहिए?",
    a: "BSCC के लिए ये दस्तावेज़ जरूरी हैं: ✅ आधार कार्ड, ✅ 12वीं मार्कशीट, ✅ आय प्रमाणपत्र (₹4.5 लाख से कम), ✅ बैंक खाता विवरण, ✅ Bihar Domicile Certificate, ✅ College Admission Letter, ✅ पासपोर्ट साइज फोटो। Siksha Wallah BSCC application की पूरी प्रक्रिया में मदद करता है — बिल्कुल निःशुल्क।",
  },
  {
    q: "क्या सभी कोर्सों पर BSCC Loan मिलता है?",
    a: "नहीं, सभी पर नहीं। BSCC Loan इन कोर्सों पर मिलता है: B.Ed, D.El.Ed, B.P.Ed, B.Sc Nursing, GNM, ANM, B.Pharma, D.Pharma, BMLT, B.Tech, Polytechnic, ITI, BCA, BBA, और अन्य 40+ courses। MBBS, BDS, MBA, MCA पर BSCC loan नहीं मिलता। हमसे confirm करें — हम सही जानकारी देंगे।",
  },

  // ── फीस व खर्च ──────────────────────────────────────────────
  {
    q: "B.Ed की fees कितनी है और BSCC से कैसे cover होगी?",
    a: "B.Ed की fees लगभग ₹50,000/वर्ष है। 2 साल में कुल ₹1,00,000। BSCC से ₹4 लाख तक loan मिलता है जो fees के साथ-साथ hostel, खाना, और किताबों के खर्च को भी cover करता है। यानी B.Ed पूरी तरह BSCC से संभव है। Siksha Wallah BSCC application में पूरी मदद करता है।",
  },
  {
    q: "Siksha Wallah की service लेने का कोई charge है?",
    a: "नहीं! Siksha Wallah की काउंसलिंग, course guidance, BSCC application सहायता, और college selection — सब बिल्कुल निःशुल्क है। हम सीधे colleges के साथ काम करते हैं। कोई बिचौलिया नहीं, कोई छिपा हुआ शुल्क नहीं। अगर कोई हमारे नाम पर पैसे मांगे तो तुरंत हमसे संपर्क करें।",
  },
];

// ── Course ID → Course data map ───────────────────────────────────────────────
export const COURSE_ID_MAP: Record<string, { course: Course; stream: StreamKey }> = {
  // Teaching
  'bed':          { course: teachingCourses[0], stream: 'teaching' },
  'deled':        { course: teachingCourses[1], stream: 'teaching' },
  'bped':         { course: teachingCourses[2], stream: 'teaching' },
  'med':          { course: teachingCourses[3], stream: 'teaching' },
  // Medical
  'mbbs':         { course: medicalCourses[0], stream: 'medical' },
  'bams':         { course: medicalCourses[1], stream: 'medical' },
  'bds':          { course: medicalCourses[2], stream: 'medical' },
  'bsc-nursing':  { course: medicalCourses[3], stream: 'medical' },
  'gnm':          { course: medicalCourses[4], stream: 'medical' },
  'anm':          { course: medicalCourses[5], stream: 'medical' },
  'dpharma':      { course: medicalCourses[6], stream: 'medical' },
  'bmlt':         { course: medicalCourses[7], stream: 'medical' },
  'bpharma':      { course: medicalCourses[8], stream: 'medical' },
  // Technical
  'btech':        { course: technicalCourses[0], stream: 'technical' },
  'polytechnic':  { course: technicalCourses[1], stream: 'technical' },
  'iti':          { course: technicalCourses[2], stream: 'technical' },
  'bca':          { course: technicalCourses[3], stream: 'technical' },
  'mca':          { course: technicalCourses[4], stream: 'technical' },
  'bba':          { course: technicalCourses[5], stream: 'technical' },
  'mba':          { course: technicalCourses[6], stream: 'technical' },
  // Paramedical
  'bpt':          { course: paramedicalCourses[0],  stream: 'paramedical' },
  'bott':         { course: paramedicalCourses[1],  stream: 'paramedical' },
  'brit':         { course: paramedicalCourses[2],  stream: 'paramedical' },
  'bmlt-para':    { course: paramedicalCourses[3],  stream: 'paramedical' },
  'bot':          { course: paramedicalCourses[4],  stream: 'paramedical' },
  'bsc-biotech':  { course: paramedicalCourses[5],  stream: 'paramedical' },
  'hospital-mgmt':{ course: paramedicalCourses[6],  stream: 'paramedical' },
  'dmlt':         { course: paramedicalCourses[7],  stream: 'paramedical' },
  'dota':         { course: paramedicalCourses[8],  stream: 'paramedical' },
  'dmr':          { course: paramedicalCourses[9],  stream: 'paramedical' },
  'opt':          { course: paramedicalCourses[10], stream: 'paramedical' },
  'ofcg':         { course: paramedicalCourses[11], stream: 'paramedical' },
  'dresser':      { course: paramedicalCourses[12], stream: 'paramedical' },
  // Law
  'llb':          { course: lawCourses[0], stream: 'law' },
  'ba-llb':       { course: lawCourses[1], stream: 'law' },
  'bba-llb':      { course: lawCourses[2], stream: 'law' },
  'llm':          { course: lawCourses[3], stream: 'law' },
};

// Helper: resolve course name to its URL slug
export function getCourseSlug(name: string): string | null {
  const lower = name.toLowerCase().replace(/[\s.]/g, '');
  for (const [slug, entry] of Object.entries(COURSE_ID_MAP)) {
    const cn = entry.course.name.toLowerCase().replace(/[\s.]/g, '');
    if (cn === lower || slug === lower) return slug;
  }
  return null;
}
