export const successStories = [
  {
    name: "Priya Singh",
    course: "B.Ed · 2024",
    place: "Forbesganj",
    text: "मैंने B.Ed में admission के लिए बहुत सी consultancy से पूछा था, लेकिन सभी ने complex process समझाया। Siksha Wallah आए तो सब कुछ बिल्कुल सरल हो गया। उन्होंने हर documentation में मेरी मदद की और admission first attempt में ही confirm हो गया।",
    avatar: "from-pink-500 to-rose-600",
  },
  {
    name: "Vikram Kumar",
    course: "B.Sc Nursing · 2024",
    place: "Araria",
    text: "Nursing course के लिए medical entrance के बाद कौन-कौन से colleges हैं, यह समझ नहीं आ रहा था। Siksha Wallah के counsellor ने सभी medical colleges की पूरी list दी, fees को समझाया, और मैंने एक अच्छी जगह से admission पाया।",
    avatar: "from-blue-500 to-cyan-600",
  },
  {
    name: "Neha Bharti",
    course: "BBA · 2024",
    place: "Forbesganj",
    text: "BBA admission पहली ही कोशिश में confirm हो गया — और कोई extra charge भी नहीं। पूरी प्रक्रिया पर पूरा भरोसा बना रहा।",
    avatar: "from-fuchsia-500 to-purple-600",
  },
  {
    name: "Sonu Kumar",
    course: "B.Pharma · 2024",
    place: "Supaul",
    text: "Pharmacy में मेरी रुचि थी, लेकिन सही जानकारी नहीं थी। यहाँ आकर सब कुछ स्पष्ट हो गया और एक अच्छे college में admission मिला।",
    avatar: "from-green-500 to-emerald-600",
  },
  {
    name: "Puja Kumari",
    course: "ANM · 2023",
    place: "Kishanganj",
    text: "ANM course के लिए सभी documents की पूरी list और प्रक्रिया यहाँ से मिली। बहुत ही आसान अनुभव — मैं इन्हें पूरे 10 में 10 दूँगी।",
    avatar: "from-sky-500 to-cyan-600",
  },
  {
    name: "Rahul Paswan",
    course: "ITI · 2024",
    place: "Forbesganj",
    text: "ITI में admission को लेकर परिवार में काफी असमंजस था। Siksha Wallah के counsellor ने हर पहलू समझाया और सही trade चुनने में मदद की।",
    avatar: "from-orange-500 to-red-600",
  },
  {
    name: "Komal Singh",
    course: "M.Ed · 2024",
    place: "Araria",
    text: "M.Ed के लिए Bihar से बाहर जाना पड़ा। Siksha Wallah ने out-of-state college में भी सहज admission दिलाया। शानदार अनुभव रहा।",
    avatar: "from-violet-500 to-indigo-600",
  },
  {
    name: "Deepak Jha",
    course: "MBA · 2023",
    place: "Purnea",
    text: "MBA के लिए BSCC loan apply किया। पूरी file Siksha Wallah team ने तैयार की और loan बिना किसी परेशानी के approve हो गया।",
    avatar: "from-teal-500 to-green-600",
  },
  {
    name: "Anita Roy",
    course: "D.El.Ed · 2024",
    place: "Supaul",
    text: "Teaching में career बनाना चाहती थी पर नहीं पता था कि D.El.Ed या B.Ed कौन सा course सही है। Siksha Wallah के विस्तृत guidance से सब कुछ clear हो गया।",
    avatar: "from-red-500 to-pink-600",
  },
  {
    name: "Nikhil Verma",
    course: "B.Tech · 2024",
    place: "Forbesganj",
    text: "Engineering college admission के लिए काफी confusing था। यहाँ technical guidance और fee breakdown दोनों मिल गए। बहुत बेहतरीन service!",
    avatar: "from-emerald-500 to-teal-600",
  },
  {
    name: "Simran Sharma",
    course: "GNM · 2023",
    place: "Araria",
    text: "Nursing के लिए सभी hospital के साथ उनके contacts थे। मुझे एक reputed hospital में placement भी मिल गई admission के साथ ही।",
    avatar: "from-amber-500 to-yellow-600",
  },
  {
    name: "Ravi Singh",
    course: "MBA · 2024",
    place: "Kishanganj",
    text: "Post-graduation के लिए सही college select करना मुश्किल था। Siksha Wallah ने placement record और fees दोनों को compare करके सही choice दी।",
    avatar: "from-indigo-500 to-blue-600",
  },
] as const;
