"use client";

import { useState } from "react";
import Link from "next/link";
import { PortalShell } from "@/components/portal-shell";
import { ArrowRight, LockKeyhole, Mail, ShieldCheck } from "lucide-react";

export default function StudentLogin() {
  const [mode,setMode]=useState<"login"|"register">("login"); const [message,setMessage]=useState("");
  const submit=(e:React.FormEvent)=>{e.preventDefault();setMessage("Firebase credentials connect hone ke baad secure account access activate hoga.")};
  return <PortalShell><section className="container-shell grid min-h-[680px] items-center gap-12 py-16 lg:grid-cols-2"><div><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#1357e6]">Student access</p><h1 className="mt-3 font-display text-4xl font-extrabold sm:text-5xl">Your education journey, organised in one dashboard.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">Track applications, documents, payments, counselling sessions, classes and notices securely.</p><div className="mt-8 space-y-3 text-sm font-bold">{["Secure student profile","Live application tracking","Documents and payment receipts","Classes, notes and notifications"].map(x=><p key={x} className="flex gap-2"><ShieldCheck size={18} className="text-emerald-500"/>{x}</p>)}</div></div><form onSubmit={submit} className="rounded-3xl border bg-white p-7 shadow-xl shadow-slate-200/60 sm:p-9"><div className="flex rounded-xl bg-slate-100 p-1"><button type="button" onClick={()=>setMode("login")} className={`flex-1 rounded-lg py-2.5 text-sm font-extrabold ${mode==="login"?"bg-white shadow":""}`}>Login</button><button type="button" onClick={()=>setMode("register")} className={`flex-1 rounded-lg py-2.5 text-sm font-extrabold ${mode==="register"?"bg-white shadow":""}`}>Create account</button></div><h2 className="mt-7 font-display text-2xl font-extrabold">{mode==="login"?"Welcome back":"Create student account"}</h2>{message&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs font-bold text-amber-700">{message}</p>}<div className="mt-5 space-y-4">{mode==="register"&&<input required placeholder="Full name" className="w-full rounded-xl border px-4 py-3.5"/>}<label className="relative block"><Mail className="absolute left-4 top-4 text-slate-400" size={18}/><input required type="email" placeholder="Email address" className="w-full rounded-xl border py-3.5 pl-12 pr-4"/></label><label className="relative block"><LockKeyhole className="absolute left-4 top-4 text-slate-400" size={18}/><input required type="password" placeholder="Password" className="w-full rounded-xl border py-3.5 pl-12 pr-4"/></label><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#1357e6] py-4 font-extrabold text-white">{mode==="login"?"Secure login":"Create account"}<ArrowRight size={18}/></button></div><div className="mt-5 text-center"><Link href="/student-dashboard" className="text-xs font-bold text-[#1357e6]">View dashboard preview</Link></div></form></section></PortalShell>;
}
